source "https://supermarket.chef.io"
cookbook 'nodejs', '~> 3.0.0'
cookbook 'build-essential', '= 3.2.0'
cookbook 'apt', '= 3.0.0'
cookbook 'windows', '= 1.44.1'
cookbook 'chef_handler', '= 1.4.0'
cookbook 'homebrew', '= 2.0.4'
cookbook 'ohai', '= 3.0.1'
