source "https://supermarket.chef.io"
cookbook 'nodejs', '~> 3.0.0'
cookbook 'build-essential', '= 3.2.0'
cookbook 'apt', '= 3.0.0'
cookbook 'windows', '= 1.44.1'
cookbook 'chef_handler', '= 1.4.0'
cookbook 'homebrew', '= 1.13.0'
cookbook 'ohai', '= 3.0.1'
# cookbook 'iptables', '= 1.1.0'
cookbook 'ark', '= 1.2.0'
cookbook 'mysql', '= 7.2.0'
cookbook 'yum-epel', '= 0.7.1'

